services:
  - type: web
    name: erp-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      # Internamente se comunican por localhost en los puertos que ya definimos
      - key: USER_SERVICE_URL
        value: http://localhost:3001
      - key: TICKETS_SERVICE_URL
        value: http://localhost:3002
      - key: GROUPS_SERVICE_URL
        value: http://localhost:3003
      - key: PORT
        value: 3000 # El puerto que expone Render será el de la Gateway
